# Exported from Render on 2026-03-01T18:43:29Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: transitguard
      runtime: node
      repo: https://github.com/GermainGihozo/transitguard
      plan: free
      envVars:
      - key: DATABASE_URL
        sync: false
      - key: RATE_LIMIT_MAX
        sync: false
      - key: BIOMETRIC_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false
      - key: NODE_ENV
        sync: false
      region: oregon
      buildCommand: npm install && npm run build
      startCommand: npm start
      healthCheckPath: /
      autoDeployTrigger: commit
